version: '3.3'

services:
  airsonic-refix:
    image: polhaghverdian/airsonic-refix
    container_name: airsonic-refix
    hostname: airsonic
    restart: always
    environment:
      - BASE_URL=airsonic
      #- SERVER_URL=https://example.com
    ports:
      - 80:80
