version: '3.3'

services:
  portainer:
    container_name: airsonic-refix
    hostname: portainer
    image: airsonic-refix
    restart: always
#    environment:
#      - BASE_URL=/airsonic
#      - SERVER_URL=https://bajskorv.com
    ports:
      - 80:80
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./data:/data
